# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 04:10
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180126_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meta',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
